project/account/urls.py
from django.urls import path
from .views import RegisterUser, LogoutView, LoginFormView, ProfileView, HandledPermissionView, ChangePasswordFormView


app_name="account"

urlpatterns = [
    path("login/", LoginFormView.as_view(), name="login"),
    path("authenticated/", HandledPermissionView.as_view(), name="authenticated"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("changepassword/", ChangePasswordFormView.as_view(), name="change_password"),
    path("logout/", LogoutView.as_view(template_name='account/logout.html') ,name='logout')
]

project/blog/urls.py
from django.urls import path
from .views import ListPost, CreatePost, DetailPostView, EditPostView, DeletePostView

app_name="blog"

urlpatterns = [
    path('', ListPost.as_view(), name="index"),
    path('pages/', ListPost.as_view(), name='list_post'),
    path('pages/<int:pk>/', DetailPostView.as_view(), name='detail_post'),
    path('create/', CreatePost.as_view(), name="create_post"),
    path('pages/edit/<int:pk>/', EditPostView.as_view(), name='edit_post'),
    path('pages/delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path('account/',include('account.urls')),
    path('blog/',include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from .views import AboutMeView
from blog.views import ListPost

app_name="core"

urlpatterns = [
    path('', ListPost.as_view(), name='index'),
    path('about/', AboutMeView.as_view(), name="about_me")
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/views.py
from django.views.generic import TemplateView


# Create your views here.
class AboutMeView(TemplateView):
    template_name = 'core/about.html'

project/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}


{% block header %}
	{% include 'core/header.html'%}
{% endblock header %}

{% block contenido %}
<div class="s-content">
	<div class="content__page-header">
		<h1 class="display-1">
		Sobre Mi ...
		</h1>
	</div>
    <div class="masonry-wrap">

        <div class="masonry">

            <div class="grid-sizer"></div>

            <article class="masonry__brick entry format-standard animate-this">
                    
                <div class="entry__thumb">
                        <img src="{% static 'core/images/perfilweb2.png' %}" alt="Autor">
                </div>
            </article>

			<article class="masonry__brick entry format-standard animate-this">
                <div class="entry__text">
                    <div class="entry__header">

                        <h2 class="entry__title"><a>Soy Matias Sanchez</a></h2>
                        <div class="entry__meta">
                            <span class="entry__meta-cat">
                                <a>Full Stack Developer</a> 
                                <a>and others</a>
                            </span>
                        </div>
                        
                    </div>
                    <div class="entry__excerpt">
                        <p>
                        Mi camino de desarrollador es largo, con altos y bajos momentos, ya hace 3 años vengo dedicandole mucho tiempo a la programacion, En Coderhouse termine la carrera de Full Stack Developer, luego segui con AWS Cloud Computing, Python y actualmente estoy en Desarrollo de Aplicaciones.
						Estoy en constante aprendizaje, y abierto a cualquier posibilidad que surja para poder crecer en el ambiente de programacion.
                        </p>
                    </div>
                </div>

            </article>

			<article class="masonry__brick entry format-standard animate-this">
                <div class="entry__text">
                    <div class="entry__header">

                        <h2 class="entry__title"><a>Otros Conocimientos</a></h2>
                        <div class="entry__meta">
                            <span class="entry__meta-cat">
                                <a>Cursos</a> 
                                <a>and others</a>
                            </span>
                        </div>
                        
                    </div>
                    <div class="entry__excerpt">
						<p>UTN Universidad Tecnica Nacional</p>
                        <ul>
							<li><p>Exper. Ethical Hacking</p></li>
						</ul>
						<p>Consultora ARPAC-IT</p>
                        <ul>
							<li><p>Ethical Hacking</p></li>
							<li><p>Forense Informatico</p></li>
							<li><p>OSINT</p></li>
							<li><p>Wireless & Mobile Hacking</p></li>
						</ul>
                    </div>
                </div>

            </article>

			<article class="masonry__brick entry format-standard animate-this">
                <div class="entry__text">
                    <div class="entry__header">

                        <h2 class="entry__title"><a>Seguime!..</a></h2>
                        <div class="entry__meta">
                            <span class="entry__meta-cat">
                                <a>Redes Sociales</a> 
                            </span>
                        </div>
                        
                    </div>
                    <ul class="header__social">
						<li class="ss-github">
							<a href="http://www.github.com/matsanchez">
								<span class="screen-reader-text">Github</span>
							</a>
						</li>
						<li class="ss-linkedin">
							<a href="http://www.linkedin.com/in/mmatsanchez">
								<span class="screen-reader-text">Linkedin</span>
							</a>
						</li>
					</ul>
                </div>

            </article>
			
        </div> 

    </div> 

</div>
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="es">
    <head>
        <meta charset="utf-8">
        <title>Proyecto Python - Msanchez</title>
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/vendor.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/main.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{% static 'core/js/modernizr.js' %}"></script>
    </head>

	<body>
        {% block header %}
            {% include 'core/header.html' %}
        {% endblock header %}
        
        {% block contenido %}
        {% endblock contenido %}

        {% include 'core/footer.html' %} 
		{% include 'core/scripts.html' %}
	</body>

</html>

project/core/templates/core/footer.html
{% load static %}
<footer class="s-footer">
    <div class="row">
        <div class="column large-full footer__content">
            <div class="footer__copyright">
                <span>Proyecto Final Python-Coderhouse</span> 
                <span>Design by Matias Sanchez</span>
            </div>
        </div>
    </div>

    <div class="go-top">
        <a class="smoothscroll" title="Back to Top" href="#top"></a>
    </div>
</footer>

project/core/templates/core/header.html
{% load static %}
<header class="s-header">

    <div class="header__top">
        <div class="header__logo">
            <a class="site-logo" href="{% url 'core:index' %}">
                <img src="{% static 'core/images/logoheader.jpg' %}" alt="Homepage">
            </a>
        </div>

    </div>
    
    <a href="#0" class="header__menu-toggle"><span>Menu</span></a>

    <nav class="header__nav-wrap">

        <ul class="header__nav">
            <li class="has-children">
                {% if user.is_authenticated %}
                    <a href="#0" title=""><img src="{{user.profile.avatar.url}}" style="width: 60px; height: 60px; border-radius: 50%;"> Hola {{user.username}}
                    {% else %}
                    <a href="#0" title=""><i class="fa fa-user fa-2x me-2" aria-hidden="true"></i>Hola {% if user.is_authenticated %} {{user.username}} {% else  %} Invitado {% endif %}</a>
                {% endif %}

                <ul class="sub-menu">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'account:profile' %}">Editar Perfil</a></li>
                        <a href="" role="button" data-bs-toggle="modal" data-bs-target="#logoutModal">Cerrar Sesion</a>
                    {% else %}
                        <li><a href="{% url 'account:login' %}">Iniciar Sesion</a></li>
                        <li><a href="{% url 'account:register' %}">Registrate</a></li>
                    {% endif %}
                </ul>
            </li>
            <li class="current"><a href="{% url 'core:index' %}" title="">Home</a></li>
            <li class="has-children">
                <a href="#0" title="">Blog</a>
                <ul class="sub-menu">
                <li><a href="{% url 'blog:list_post' %}">Ver Posts</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'blog:create_post' %}">Crear un Post</a></li>
                {% endif %}
                </ul>
            </li>
            <li><a href="{% url 'core:about_me' %}" title="">Sobre mi</a></li>
        </ul> <!-- end header__nav -->

        <ul class="header__social">
            <li class="ss-github">
                <a href="http://www.github.com/matsanchez">
                    <span class="screen-reader-text">Github</span>
                </a>
            </li>
            <li class="ss-linkedin">
                <a href="http://www.linkedin.com/in/mmatsanchez">
                    <span class="screen-reader-text">Linkedin</span>
                </a>
            </li>
        </ul>

    </nav>
</header>

<div class="modal fade " id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-body">
            <p>¿Seguro de cerrar sesion?</p>
            <h3>{{user.username}}</h3>
          <form action="{% url 'account:logout' %}" method="POST">
            {% csrf_token %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-bs-dismiss="modal">NO</button>
          <button type="submit" class="btn btn-danger">Si, salir</button>
        </div>
      </form>
      </div>
    </div>
  </div>

project/core/templates/core/scripts.html
{% load static %}
    <script src="{% static 'core/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/js/plugins.js' %}"></script>
    <script src="{% static 'core/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>