project/blog/urls.py
from django.urls import path
from .views import ListPost, CreatePost, DetailPostView, EditPostView, DeletePostView

app_name="blog"

urlpatterns = [
    path('', ListPost.as_view(), name="index"),
    path('pages/', ListPost.as_view(), name='list_post'),
    path('pages/<int:pk>/', DetailPostView.as_view(), name='detail_post'),
    path('create/', CreatePost.as_view(), name="create_post"),
    path('pages/edit/<int:pk>/', EditPostView.as_view(), name='edit_post'),
    path('pages/delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path('account/',include('account.urls')),
    path('blog/',include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

    
class Post(models.Model):
    title=models.CharField(max_length=100, verbose_name='Titulo')
    subtitle=models.CharField(max_length=100, verbose_name='Subtitulo')
    body=RichTextField(max_length=500, verbose_name='Experiencia')
    author=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Autor')
    date=models.DateTimeField(auto_now_add=True)
    image=models.ImageField(upload_to="posts/",null=False, blank=False,verbose_name='Imagen')

    def __str__(self):
        return f'{self.title} {self.subtitle}'

project/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'subtitle', 'body', 'image']
        labels = {
                'title': 'Titulo del Post',
                'subtitle': 'Subtitulo',
                'body': 'Ingrese su experiencia',
                'image': 'Subi una imagen',
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'full-width bg-transparent'})
            field.widget.attrs['placeholder'] = self.Meta.labels.get(field_name, '')

project/blog/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.urls.base import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from message.forms import MessagePostForm
from .models import Post
from .forms import PostForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

# Create your views here.
class ListPost(ListView):
    model= Post
    template_name = 'blog/list_post.html'
    context_object_name = 'posts'


class DetailPost(DetailView):
    model= Post
    template_name='blog/detail_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = MessagePostForm()
        return context


class PostCommentFormView(LoginRequiredMixin,SingleObjectMixin, FormView):
    template_name='blog/detail_post.html'
    form_class = MessagePostForm
    model = Post
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args,**kwargs)
    
    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.post = self.object
        f.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blog:detail_post', kwargs={'pk': self.object.id}) + '#comments-section'


class DetailPostView(View):
    def get(self, request, *args, **kwargs):
        view = DetailPost.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostCommentFormView.as_view()
        return view(request, *args, **kwargs)
    

class CreatePost(LoginRequiredMixin,CreateView):
    model = Post
    template_name = 'blog/create_post.html'
    form_class = PostForm
    login_url = reverse_lazy('account:login')

    def test_func(self):
        # Este método se llama para determinar si el usuario pasa la prueba.
        # Devuelve True si el usuario puede acceder, False de lo contrario.
        return not self.request.user.is_authenticated
    
    def post(self, request, *args, **kwargs):
        logged_in_user = request.user
        form=PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = logged_in_user
            new_post.save()
            pk = new_post.id
            messages.add_message(request=request, level=messages.SUCCESS, message="¡Post Creado Exitosamente!")
        return redirect(f'/blog/pages/{pk}')
    

class EditPostView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model=Post
    fields=['title','subtitle', 'body', 'image']
    template_name = 'blog/edit_post.html'
    login_url = reverse_lazy('account:login')

    def post(self, request, *args, **kwargs):
        messages.add_message(self.request,level=messages.SUCCESS, message="¡El post fue editado correctamente!")
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail_post', kwargs={'pk':pk})
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    

class DeletePostView(LoginRequiredMixin,UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list_post')
    login_url = reverse_lazy('account:login')
    
    def test_func(self):
        messages.add_message(self.request,level=messages.INFO, message="¡El Post fue eliminado Correctamente!")
        post = self.get_object()
        return self.request.user == post.author

project/blog/templates/blog/create_post.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html'%}
{% endblock header %}

{% block contenido %}
<div class="s-content content">
    <main class="row content__page">
        
        <section class="column large-full entry format-standard">

            <div class="content__page-header">
                <h1 class="display-1">
                Crear un Post
                </h1>
            </div> <!-- end content__page-header -->
        
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <div class="form-control bg-transparent border-0">
                    {{ field }}
                {% for error in field.errors %}
                    <div class="error-message"><p class="text-danger fs-5">{{ error }}</p></div>
                    {% endfor %}
                    </div>
                 {% endfor %}
                    <input name="submit" id="submit" class="btn btn--primary btn-wide btn--large full-width" value="Crear Post" type="submit">
                </fieldset>
                {{form.errors}}
            </form>
            
        </section>

    </main>

</div>
{% endblock contenido %}

project/blog/templates/blog/delete_post.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with title="Editando tu Post" description_section="Retoca tu publicacion y volvela a guardar"%}
{% endblock header %}

{% block contenido %}
<h1>BORRADO</h1>
{% endblock contenido %}

project/blog/templates/blog/detail_post.html
{% extends 'core/base.html' %}
{% load static %}
{% block header %}
    {% include 'core/header.html'%}
{% endblock header %}

{% block contenido %}
<div class="s-content content" id="top">
    {% for message in messages %}
            {% if message.tags == 'success' %}
                    <script>
                        Swal.fire({
                                position: "top-end",
                                icon: "success",
                                title: "{{message}}",
                                showConfirmButton: false,
                                timer: 1500
                                });
                    </script>
            {% elif message.tags == 'info' %}
                    <script>
                        Swal.fire({
                                position: "top-end",
                                icon: "info",
                                title: "{{message}}",
                                showConfirmButton: false,
                                timer: 1500
                                });
                    </script>
            {% endif %}
    {% endfor %}
   
  <main class="row content__page">
      
      <article class="column large-full entry format-standard">

          <div class="media-wrap entry__media">
            <div class="d-flex justify-content-between mb-3">
                <div class="d-flex align-items-center">
                    <a href="{% url 'blog:list_post'%}" class="d-flex align-content-center">
                        <i class="fa fa-arrow-left fa-fw fa-2x me-2" aria-hidden="true"></i>Volver
                    </a>
                </div>                
                <div>
                    {% if user.is_authenticated %}
                    {% if post.author == request.user %}
                    <div class="dropdown">
                        <i class="fa fa-ellipsis-h fa-2x" role="button" type="button"  data-bs-toggle="dropdown" aria-expanded="false"></i>
                        <ul class="dropdown-menu">
                            <a class="list-group-item" href="{% url 'blog:edit_post' post.pk %}"><i class="fa fa-cog fa-fw" aria-hidden="true"></i>EDITAR</a>
                            <a class="list-group-item" role="button" data-bs-toggle="modal" data-bs-target="#deleteModal"><i class="fa fa-trash fa-fw" aria-hidden="true"></i>BORRAR</a>
                        </ul>
                    </div>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
            
            
         
              <div class="entry__post-thumb text-center">
                  <img src="{{post.image.url}}" 
                       srcset="{{post.image.url}}, 
                       {{post.image.url}}, 
                       {{post.image.url}}" sizes="(max-width: 2000px) 100vw, 2000px" alt="">
              </div>
          </div>

          <div class="content__page-header entry__header">
              <h1 class="display-1 entry__title">
              {{post.title}}
              </h1>
              
              <ul class="entry__header-meta">
                <p class="fs-1">
                    {{post.subtitle}}
                    </p>
                  <li class="author"><i class="fa fa-user fa-1x" aria-hidden="true"></i>
                    {{post.author}}</li>
                  <li class="date">{{post.date}}</li>
              </ul>
          </div>

          <div class="entry__content">

              <p>
              {{post.body | safe}}
              </p>
          </div>

      </article>


      <div class="comments-wrap bg-transparent">

          <div id="comments" class="column large-12">

              <h3 class="h2">Comentarios</h3>
              <ol class="commentlist mt-0"  id="comments-section">
                {% if post.comments.all %}
                    {% else %}
                    <div class="text-center"><h4 class="text-danger">No hay comentarios aún...</h4></div>
                {% endif %}
                  {% for comment in post.comments.all %}
                      <li>
                            <div class="p-2">
                              <div class="comment__info">
                                  <div class="comment__author"><i class="fa fa-user" aria-hidden="true"></i> {{comment.author}}</div>

                                  <div class="comment__meta">
                                      <div class="comment__time">{{comment.date | date:"d-M-Y"}}</div>
                                      <div class="comment__reply">
                                          
                                      </div>
                                  </div>
                              </div>

                              <div class="comment__text">
                                    <p><span class="text-muted fst-italic">Dice:</span> {{comment.body}}</p>
                              </div>
                            </div>  
                      </li>
                      <hr> 
                  {% endfor %}
              </ol>
             

          </div> 

          <div class="column large-12 comment-respond">

              
              {% if user.is_authenticated %}
                <div id="respond">
    
                        <h3 class="h2">Dejanos tu comentario<span>Tu correo no se mostrara en el comentario</span></h3>

                        <form method="POST" action="" autocomplete="off">
                        {% csrf_token %}
                            <fieldset>

                                <div class="form-field">
                                    <input name="name" id="{{user.username}}" class="full-width" value="{{user.username}}" type="text" disabled>
                                </div>

                                <div class="form-field">
                                    <input name="email" id="{{user.email}}" class="full-width" value="{{user.email}}" type="text" disabled>
                                </div>
        
                                <div class="message form-field">
                                    <textarea name="body" id="cMessage" class="full-width" placeholder="Tu comentario" required></textarea>
                                </div>

                                <input name="submit" id="submit" class="btn btn--primary btn-wide btn--large full-width" value="Enviar Comentario" type="submit">

                            </fieldset>
                        </form> 

                    </div>
              {% endif %}
              
  
          </div> 
  
      </div> 
  </main>

</div>

<!-- MODAL ALERTA DE BORRAR POST -->
<div class="modal fade " id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <blockquote>
          <p>Estas por eliminar el post:</p>
          <h3>{{post.title}}</h3>
          <cite>Creada by {{post.author}}</cite>
      </blockquote>
        <form action="{% url 'blog:delete_post' post.pk %}" method="POST">
          {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-danger">Borrar</button>
      </div>
    </form>
    </div>
  </div>
</div>
<!-- FIN DEL MODAL ALERTA BORRAR POST -->
</div>
    </div>
  </div>
{% endblock contenido %}

project/blog/templates/blog/edit_post.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html'%}
{% endblock header %}

{% block contenido %}
<div class="s-content content">
    <main class="row content__page">
        
        <section class="column large-full entry format-standard">

            <div class="content__page-header">
                <h1 class="display-1">
                Editar Post
                </h1>
            </div> <!-- end content__page-header -->
        
            <form method="POST" enctype="multipart/form-data">
                <div class="row">
                    {% csrf_token %}
                    {% for label in form %}
                        <div class="form-group">
                            <label for="{{ label.id_for_label }}">{{ label.label }}</label>
                            {% if label.name != 'body' %}
                                <input type="{{ label.field.widget.input_type }}" name="{{ label.name }}" id="{{ label.id_for_label }}" value="{{ label.value }}"
                                       class="form-control">
                            {% else %}
                                <textarea cols='80' rows="10" type="{{ label.field.widget.input_type }}" name="{{ label.name }}" id="{{ label.id_for_label }}"
                                          class="form-control">{{ label.value }}</textarea>
                            {% endif %}
                            
                            {% for error in label.errors %}
                                <div class="error-message">
                                    <p class="text-danger fs-5">{{ error }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                
                    <button type="submit" class="btn btn-primary-hover-outline mt-2">Actualizar Post</button>
                </div>
            </form>
            
        </section>

    </main>

</div>
{% endblock contenido %}

project/blog/templates/blog/index.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with title="Tu blog" description_section="Aqui encontraras experiencias de viajeros y tambien podes compartir tu experiencia para que otros usuarios la vean" %}
{% endblock header %}

{% block contenido %}
    <h1>CONTENIDO PARA EL BLOG</h1>
{% endblock contenido %}

project/blog/templates/blog/list_post.html
{% extends 'core/base.html' %}
{% block header %}
    {% include 'core/header.html'%}
{% endblock header %}

{% block contenido %}
<div class="s-content" id="top">
    {% for message in messages %}
            {% if message.tags == 'success' %}
                    <script>
                        Swal.fire({
                                position: "top-end",
                                icon: "success",
                                title: "{{message}}",
                                showConfirmButton: false,
                                timer: 1500
                                });
                    </script>
            {% elif message.tags == 'info' %}
                    <script>
                        Swal.fire({
                                position: "top-end",
                                icon: "info",
                                title: "{{message}}",
                                showConfirmButton: false,
                                timer: 1500
                                });
                    </script>
            {% endif %}
    {% endfor %}

    <div class="masonry-wrap">

        <div class="masonry">

            <div class="grid-sizer"></div>
                {% for post in posts  %}
                <article class="masonry__brick entry format-standard animate-this">
                    
                    <div class="entry__thumb">
                        <a href="{% url 'blog:detail_post' post.pk %}" class="entry__thumb-link">
                            <img src="{{post.image.url}}" 
                                    srcset="{{post.image.url}} 1x, {{post.image.url}} 2x" alt="">
                        </a>
                    </div>
    
                    <div class="entry__text">
                        <div class="entry__header">
    
                            <h2 class="entry__title"><a role="button" href="{% url 'blog:detail_post' post.pk %}">{{post.title}}</a></h2>
                            <div class="entry__meta">
                                <span class="entry__meta-cat">
                                    <p><i class="fa fa-user" aria-hidden="true"></i>{{post.author}}</p>
                                </span>
                                <span class="entry__meta-date">
                                    <p>{{post.date}}</p>
                                </span>
                            </div>
                            
                        </div>
                        <div class="entry__excerpt mb-4">
                            <p>
                            {{post.body | safe}}
                            </p>
                        </div>
                        <a class="mt-4" href="{% url 'blog:detail_post' post.pk %}"><p class="fs-5">Seguir leyendo...</p></a>
                    </div>
                    
                </article>
                {% endfor %}
            
        </div>

    </div> 

</div>
{% endblock contenido %}